[package]
name = "textgametest"
version = "0.1.0"
authors = ["Simon Goller <neosam+github@posteo.de>"]

[dependencies]
serde = "0.8"
serde_derive = { version = "0.8" }
serde_json = "0.8"  # just for the example, not required in general